import type { RecipeFormData } from "./types";

export const SEED_RECIPES: Omit<RecipeFormData, "group_ids">[] = [
  {
    title: "Grandma Rose's Sunday Pancakes",
    description:
      "Every Sunday morning, Grandma Rose would wake up before anyone else and have a stack of these fluffy pancakes waiting on the table. The secret is letting the batter rest for 10 minutes — and a pinch of nutmeg that makes them taste like home.",
    hero_url: null,
    gallery_urls: [],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    total_time_minutes: 30,
    servings: 4,
    difficulty: "Easy",
    category: "Breakfast & Brunch",
    tags: ["Kid-Friendly", "Quick & Easy", "Comfort Food"],
    status: "published",
    is_private: false,
    ingredients: [
      { quantity: "2", unit: "cups", name: "all-purpose flour", prep_note: "", sort_order: 0 },
      { quantity: "2", unit: "tbsp", name: "sugar", prep_note: "", sort_order: 1 },
      { quantity: "2", unit: "tsp", name: "baking powder", prep_note: "", sort_order: 2 },
      { quantity: "1/2", unit: "tsp", name: "salt", prep_note: "", sort_order: 3 },
      { quantity: "1/4", unit: "tsp", name: "nutmeg", prep_note: "freshly grated", sort_order: 4 },
      { quantity: "2", unit: "", name: "eggs", prep_note: "large", sort_order: 5 },
      { quantity: "1 3/4", unit: "cups", name: "milk", prep_note: "", sort_order: 6 },
      { quantity: "1/4", unit: "cup", name: "melted butter", prep_note: "", sort_order: 7 },
    ],
    instructions: [
      { text: "Whisk together flour, sugar, baking powder, salt, and nutmeg in a large bowl.", timer_minutes: null, sort_order: 0 },
      { text: "In a separate bowl, beat eggs, then stir in milk and melted butter.", timer_minutes: null, sort_order: 1 },
      { text: "Pour wet ingredients into dry and stir until just combined. Don't overmix — lumps are okay!", timer_minutes: null, sort_order: 2 },
      { text: "Let batter rest for 10 minutes while you heat a griddle or large skillet over medium heat.", timer_minutes: 10, sort_order: 3 },
      { text: "Lightly butter the griddle. Pour 1/4 cup batter per pancake. Cook until bubbles form on surface, about 2-3 minutes.", timer_minutes: 3, sort_order: 4 },
      { text: "Flip and cook another 1-2 minutes until golden. Serve warm with maple syrup and fresh berries.", timer_minutes: 2, sort_order: 5 },
    ],
  },
  {
    title: "Dad's Famous Chili",
    description:
      "This is the chili that won the neighborhood cook-off three years running. Dad says the key is browning the meat properly and letting it simmer low and slow. We always make a double batch — it freezes beautifully.",
    hero_url: null,
    gallery_urls: [],
    prep_time_minutes: 20,
    cook_time_minutes: 90,
    total_time_minutes: 110,
    servings: 8,
    difficulty: "Medium",
    category: "Soups & Stews",
    tags: ["Comfort Food", "One-Pot", "Make-Ahead", "Freezer-Friendly"],
    status: "published",
    is_private: false,
    ingredients: [
      { quantity: "2", unit: "lb", name: "ground beef", prep_note: "85/15", sort_order: 0 },
      { quantity: "1", unit: "", name: "large onion", prep_note: "diced", sort_order: 1 },
      { quantity: "4", unit: "clove", name: "garlic", prep_note: "minced", sort_order: 2 },
      { quantity: "2", unit: "can", name: "diced tomatoes", prep_note: "14.5 oz each", sort_order: 3 },
      { quantity: "1", unit: "can", name: "kidney beans", prep_note: "drained and rinsed", sort_order: 4 },
      { quantity: "1", unit: "can", name: "black beans", prep_note: "drained and rinsed", sort_order: 5 },
      { quantity: "3", unit: "tbsp", name: "chili powder", prep_note: "", sort_order: 6 },
      { quantity: "1", unit: "tbsp", name: "cumin", prep_note: "", sort_order: 7 },
      { quantity: "1", unit: "tsp", name: "smoked paprika", prep_note: "", sort_order: 8 },
      { quantity: "2", unit: "cups", name: "beef broth", prep_note: "", sort_order: 9 },
    ],
    instructions: [
      { text: "Brown ground beef in a large Dutch oven over medium-high heat, breaking it up as it cooks. Drain excess fat.", timer_minutes: 8, sort_order: 0 },
      { text: "Add onion and garlic. Cook until softened, about 5 minutes.", timer_minutes: 5, sort_order: 1 },
      { text: "Stir in chili powder, cumin, and paprika. Cook 1 minute until fragrant.", timer_minutes: 1, sort_order: 2 },
      { text: "Add tomatoes, beans, and broth. Bring to a boil, then reduce heat to low.", timer_minutes: null, sort_order: 3 },
      { text: "Simmer uncovered for 1 hour, stirring occasionally. Taste and adjust seasoning.", timer_minutes: 60, sort_order: 4 },
      { text: "Serve with shredded cheese, sour cream, and cornbread on the side.", timer_minutes: null, sort_order: 5 },
    ],
  },
  {
    title: "Mom's Chicken Pot Pie",
    description:
      "The ultimate comfort food. Mom made this every time someone in the family was feeling under the weather. The homemade crust is worth the effort, but store-bought works in a pinch!",
    hero_url: null,
    gallery_urls: [],
    prep_time_minutes: 30,
    cook_time_minutes: 45,
    total_time_minutes: 75,
    servings: 6,
    difficulty: "Medium",
    category: "Dinner",
    tags: ["Comfort Food", "Kid-Friendly", "Make-Ahead"],
    status: "published",
    is_private: false,
    ingredients: [
      { quantity: "3", unit: "cup", name: "cooked chicken", prep_note: "shredded", sort_order: 0 },
      { quantity: "2", unit: "cup", name: "mixed vegetables", prep_note: "peas, carrots, corn", sort_order: 1 },
      { quantity: "1/3", unit: "cup", name: "butter", prep_note: "", sort_order: 2 },
      { quantity: "1/3", unit: "cup", name: "all-purpose flour", prep_note: "", sort_order: 3 },
      { quantity: "1 3/4", unit: "cup", name: "chicken broth", prep_note: "", sort_order: 4 },
      { quantity: "2/3", unit: "cup", name: "milk", prep_note: "", sort_order: 5 },
      { quantity: "2", unit: "", name: "pie crusts", prep_note: "9-inch, unbaked", sort_order: 6 },
      { quantity: "1", unit: "tsp", name: "poultry seasoning", prep_note: "", sort_order: 7 },
    ],
    instructions: [
      { text: "Preheat oven to 425°F (220°C).", timer_minutes: null, sort_order: 0 },
      { text: "Melt butter in a saucepan. Stir in flour, salt, and pepper until smooth. Gradually whisk in broth and milk.", timer_minutes: null, sort_order: 1 },
      { text: "Cook sauce until thick and bubbly, about 5 minutes. Stir in chicken, vegetables, and poultry seasoning.", timer_minutes: 5, sort_order: 2 },
      { text: "Pour filling into bottom pie crust. Cover with top crust, seal edges, and cut slits in top.", timer_minutes: null, sort_order: 3 },
      { text: "Bake 30-35 minutes until crust is golden brown. Let cool 10 minutes before serving.", timer_minutes: 35, sort_order: 4 },
    ],
  },
  {
    title: "Aunt Maria's Chocolate Chip Cookies",
    description:
      "These cookies are legendary in our family. Aunt Maria brought them to every gathering for 40 years. The dough must be chilled overnight — no shortcuts! They come out perfectly chewy with crispy edges.",
    hero_url: null,
    gallery_urls: [],
    prep_time_minutes: 15,
    cook_time_minutes: 12,
    total_time_minutes: 27,
    servings: 36,
    difficulty: "Easy",
    category: "Desserts",
    tags: ["Kid-Friendly", "Make-Ahead", "Holiday"],
    status: "published",
    is_private: false,
    ingredients: [
      { quantity: "2 1/4", unit: "cups", name: "all-purpose flour", prep_note: "", sort_order: 0 },
      { quantity: "1", unit: "tsp", name: "baking soda", prep_note: "", sort_order: 1 },
      { quantity: "1", unit: "tsp", name: "salt", prep_note: "", sort_order: 2 },
      { quantity: "1", unit: "cup", name: "butter", prep_note: "softened", sort_order: 3 },
      { quantity: "3/4", unit: "cup", name: "granulated sugar", prep_note: "", sort_order: 4 },
      { quantity: "3/4", unit: "cup", name: "brown sugar", prep_note: "packed", sort_order: 5 },
      { quantity: "2", unit: "", name: "eggs", prep_note: "large", sort_order: 6 },
      { quantity: "2", unit: "tsp", name: "vanilla extract", prep_note: "", sort_order: 7 },
      { quantity: "2", unit: "cups", name: "chocolate chips", prep_note: "semi-sweet", sort_order: 8 },
    ],
    instructions: [
      { text: "Whisk flour, baking soda, and salt together in a bowl.", timer_minutes: null, sort_order: 0 },
      { text: "Cream butter and both sugars until light and fluffy, about 3 minutes.", timer_minutes: 3, sort_order: 1 },
      { text: "Beat in eggs one at a time, then vanilla.", timer_minutes: null, sort_order: 2 },
      { text: "Gradually mix in flour mixture, then fold in chocolate chips.", timer_minutes: null, sort_order: 3 },
      { text: "Cover dough and refrigerate at least 2 hours (overnight is best).", timer_minutes: 120, sort_order: 4 },
      { text: "Preheat oven to 375°F. Drop rounded tablespoons onto ungreased baking sheets.", timer_minutes: null, sort_order: 5 },
      { text: "Bake 9-11 minutes until golden. Cool on baking sheet 2 minutes before transferring.", timer_minutes: 11, sort_order: 6 },
    ],
  },
  {
    title: "Simple Weeknight Pasta",
    description:
      "When everyone's hungry and nobody wants to cook, this 20-minute pasta saves the day. Even the little ones can help stir the sauce!",
    hero_url: null,
    gallery_urls: [],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    total_time_minutes: 20,
    servings: 4,
    difficulty: "Easy",
    category: "Dinner",
    tags: ["Quick & Easy", "Kid-Friendly", "One-Pot", "Vegetarian"],
    status: "published",
    is_private: false,
    ingredients: [
      { quantity: "1", unit: "lb", name: "spaghetti", prep_note: "", sort_order: 0 },
      { quantity: "3", unit: "tbsp", name: "olive oil", prep_note: "", sort_order: 1 },
      { quantity: "4", unit: "clove", name: "garlic", prep_note: "thinly sliced", sort_order: 2 },
      { quantity: "1/4", unit: "tsp", name: "red pepper flakes", prep_note: "optional", sort_order: 3 },
      { quantity: "1/4", unit: "cup", name: "fresh parsley", prep_note: "chopped", sort_order: 4 },
      { quantity: "1/2", unit: "cup", name: "Parmesan cheese", prep_note: "grated", sort_order: 5 },
    ],
    instructions: [
      { text: "Cook pasta in salted boiling water according to package directions. Reserve 1 cup pasta water before draining.", timer_minutes: 10, sort_order: 0 },
      { text: "While pasta cooks, heat olive oil in a large skillet over medium heat. Add garlic and red pepper flakes.", timer_minutes: null, sort_order: 1 },
      { text: "Cook garlic until golden, about 2 minutes. Don't let it burn!", timer_minutes: 2, sort_order: 2 },
      { text: "Add drained pasta to skillet with a splash of pasta water. Toss to coat.", timer_minutes: null, sort_order: 3 },
      { text: "Remove from heat. Stir in parsley and Parmesan. Serve immediately.", timer_minutes: null, sort_order: 4 },
    ],
  },
  {
    title: "Grandpa's Apple Crisp",
    description:
      "Grandpa picked apples from the backyard tree every fall for this crisp. He'd let us kids help crumble the topping — and sneak apple slices while we worked. Best served warm with vanilla ice cream.",
    hero_url: null,
    gallery_urls: [],
    prep_time_minutes: 20,
    cook_time_minutes: 45,
    total_time_minutes: 65,
    servings: 8,
    difficulty: "Easy",
    category: "Desserts",
    tags: ["Comfort Food", "Kid-Friendly", "Holiday"],
    status: "published",
    is_private: false,
    ingredients: [
      { quantity: "6", unit: "", name: "apples", prep_note: "peeled, sliced", sort_order: 0 },
      { quantity: "1/2", unit: "cup", name: "sugar", prep_note: "", sort_order: 1 },
      { quantity: "1", unit: "tsp", name: "cinnamon", prep_note: "", sort_order: 2 },
      { quantity: "1", unit: "cup", name: "oats", prep_note: "rolled", sort_order: 3 },
      { quantity: "1", unit: "cup", name: "flour", prep_note: "", sort_order: 4 },
      { quantity: "1/2", unit: "cup", name: "brown sugar", prep_note: "packed", sort_order: 5 },
      { quantity: "1/2", unit: "cup", name: "butter", prep_note: "cold, cubed", sort_order: 6 },
    ],
    instructions: [
      { text: "Preheat oven to 350°F (175°C). Grease a 9x13 baking dish.", timer_minutes: null, sort_order: 0 },
      { text: "Toss apple slices with sugar and cinnamon. Spread evenly in baking dish.", timer_minutes: null, sort_order: 1 },
      { text: "In a bowl, combine oats, flour, and brown sugar. Cut in butter until crumbly.", timer_minutes: null, sort_order: 2 },
      { text: "Sprinkle topping evenly over apples.", timer_minutes: null, sort_order: 3 },
      { text: "Bake 40-45 minutes until topping is golden and apples are tender.", timer_minutes: 45, sort_order: 4 },
      { text: "Let cool 10 minutes. Serve warm with vanilla ice cream.", timer_minutes: 10, sort_order: 5 },
    ],
  },
  {
    title: "Holiday Green Bean Casserole",
    description:
      "No Thanksgiving table is complete without this casserole. It's been in the family since the 1960s. We always double the fried onions on top — half mixed in, half sprinkled on at the end for crunch.",
    hero_url: null,
    gallery_urls: [],
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    total_time_minutes: 45,
    servings: 10,
    difficulty: "Easy",
    category: "Holiday & Special Occasions",
    tags: ["Holiday", "Comfort Food", "Make-Ahead"],
    status: "published",
    is_private: false,
    ingredients: [
      { quantity: "2", unit: "can", name: "green beans", prep_note: "drained", sort_order: 0 },
      { quantity: "1", unit: "can", name: "cream of mushroom soup", prep_note: "10.5 oz", sort_order: 1 },
      { quantity: "1/2", unit: "cup", name: "milk", prep_note: "", sort_order: 2 },
      { quantity: "1", unit: "tsp", name: "soy sauce", prep_note: "", sort_order: 3 },
      { quantity: "1", unit: "package", name: "fried onions", prep_note: "6 oz, divided", sort_order: 4 },
      { quantity: "1/4", unit: "tsp", name: "black pepper", prep_note: "", sort_order: 5 },
    ],
    instructions: [
      { text: "Preheat oven to 350°F (175°C).", timer_minutes: null, sort_order: 0 },
      { text: "Mix green beans, soup, milk, soy sauce, pepper, and half the fried onions in a 2-quart baking dish.", timer_minutes: null, sort_order: 1 },
      { text: "Bake uncovered for 25 minutes.", timer_minutes: 25, sort_order: 2 },
      { text: "Top with remaining fried onions. Bake 5 more minutes until onions are golden.", timer_minutes: 5, sort_order: 3 },
    ],
  },
  {
    title: "Kids' Smoothie Bowls",
    description:
      "The kids love making these colorful smoothie bowls on Saturday mornings. Let them pick their own toppings — it's half the fun!",
    hero_url: null,
    gallery_urls: [],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    total_time_minutes: 10,
    servings: 2,
    difficulty: "Easy",
    category: "Kid-Friendly Favorites",
    tags: ["Kid-Friendly", "Quick & Easy", "Vegetarian", "Dairy-Free"],
    status: "published",
    is_private: false,
    ingredients: [
      { quantity: "2", unit: "", name: "frozen bananas", prep_note: "", sort_order: 0 },
      { quantity: "1", unit: "cup", name: "frozen berries", prep_note: "mixed", sort_order: 1 },
      { quantity: "1/2", unit: "cup", name: "almond milk", prep_note: "", sort_order: 2 },
      { quantity: "1", unit: "tbsp", name: "honey", prep_note: "optional", sort_order: 3 },
      { quantity: "", unit: "", name: "toppings", prep_note: "granola, coconut, fresh fruit", sort_order: 4 },
    ],
    instructions: [
      { text: "Blend frozen bananas, berries, and almond milk until thick and smooth. Add honey if desired.", timer_minutes: null, sort_order: 0 },
      { text: "Pour into bowls. Let kids decorate with their favorite toppings!", timer_minutes: null, sort_order: 1 },
      { text: "Eat immediately with spoons while still cold and thick.", timer_minutes: null, sort_order: 2 },
    ],
  },
  {
    title: "Homemade Tomato Soup & Grilled Cheese",
    description:
      "Rainy day classic. The soup is so much better than canned, and dipping grilled cheese into it is pure childhood nostalgia.",
    hero_url: null,
    gallery_urls: [],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    total_time_minutes: 35,
    servings: 4,
    difficulty: "Easy",
    category: "Lunch",
    tags: ["Kid-Friendly", "Comfort Food", "Quick & Easy", "Vegetarian"],
    status: "published",
    is_private: false,
    ingredients: [
      { quantity: "2", unit: "tbsp", name: "butter", prep_note: "", sort_order: 0 },
      { quantity: "1", unit: "", name: "onion", prep_note: "diced", sort_order: 1 },
      { quantity: "2", unit: "can", name: "crushed tomatoes", prep_note: "28 oz each", sort_order: 2 },
      { quantity: "2", unit: "cup", name: "vegetable broth", prep_note: "", sort_order: 3 },
      { quantity: "1/2", unit: "cup", name: "heavy cream", prep_note: "", sort_order: 4 },
      { quantity: "1", unit: "tsp", name: "basil", prep_note: "dried", sort_order: 5 },
      { quantity: "8", unit: "slice", name: "bread", prep_note: "for grilled cheese", sort_order: 6 },
      { quantity: "4", unit: "slice", name: "cheddar cheese", prep_note: "", sort_order: 7 },
    ],
    instructions: [
      { text: "Melt butter in a pot over medium heat. Sauté onion until soft, about 5 minutes.", timer_minutes: 5, sort_order: 0 },
      { text: "Add tomatoes, broth, and basil. Simmer 15 minutes.", timer_minutes: 15, sort_order: 1 },
      { text: "Blend until smooth (careful — it's hot!). Return to pot and stir in cream.", timer_minutes: null, sort_order: 2 },
      { text: "For grilled cheese: butter bread, add cheese, grill in a pan until golden on both sides.", timer_minutes: 5, sort_order: 3 },
      { text: "Serve soup in bowls with grilled cheese on the side for dipping.", timer_minutes: null, sort_order: 4 },
    ],
  },
  {
    title: "Fresh Garden Salad with Lemon Vinaigrette",
    description:
      "Simple, bright, and perfect alongside any meal. We grow the lettuce and herbs in our backyard garden all summer long.",
    hero_url: null,
    gallery_urls: [],
    prep_time_minutes: 15,
    cook_time_minutes: 0,
    total_time_minutes: 15,
    servings: 4,
    difficulty: "Easy",
    category: "Sides & Salads",
    tags: ["Quick & Easy", "Vegetarian", "Gluten-Free", "Vegan"],
    status: "published",
    is_private: false,
    ingredients: [
      { quantity: "6", unit: "cup", name: "mixed greens", prep_note: "", sort_order: 0 },
      { quantity: "1", unit: "cup", name: "cherry tomatoes", prep_note: "halved", sort_order: 1 },
      { quantity: "1/2", unit: "cup", name: "cucumber", prep_note: "sliced", sort_order: 2 },
      { quantity: "1/4", unit: "cup", name: "red onion", prep_note: "thinly sliced", sort_order: 3 },
      { quantity: "3", unit: "tbsp", name: "olive oil", prep_note: "", sort_order: 4 },
      { quantity: "2", unit: "tbsp", name: "lemon juice", prep_note: "fresh", sort_order: 5 },
      { quantity: "1", unit: "tsp", name: "honey", prep_note: "", sort_order: 6 },
      { quantity: "1/4", unit: "tsp", name: "salt", prep_note: "", sort_order: 7 },
    ],
    instructions: [
      { text: "Combine greens, tomatoes, cucumber, and onion in a large salad bowl.", timer_minutes: null, sort_order: 0 },
      { text: "Whisk olive oil, lemon juice, honey, and salt in a small bowl.", timer_minutes: null, sort_order: 1 },
      { text: "Drizzle dressing over salad just before serving. Toss gently and enjoy!", timer_minutes: null, sort_order: 2 },
    ],
  },
];